# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='length',
        ),
    ]
